# ===================================================================
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    jackson:
        serialization:
            indent_output: true
            write_dates_as_timestamps: false
    messages:
        cache-seconds: 1
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    http:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: app

security:
    basic:
        enabled: false

application:
    security:
        authentication:
            jwt:
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    http:
        version: V_2_0
        cache: # Used by the CachingHttpHeadersFilter
            time-to-live-in-days: 1461
    # By default CORS is disabled. Uncomment to enable.
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    cache: # Cache configuration
        hazelcast: # Hazelcast distributed cache
            time-to-live-seconds: 3600
            backup-count: 1
            local-address: 127.0.0.1
    mail:
        from: app@localhost
        base-url: http://127.0.0.1:8080
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        graphite: # Use the "graphite" Maven profile to have the Graphite dependencies
            enabled: false
            host: localhost
            port: 2003
            prefix: app
        prometheus: # Use the "prometheus" Maven profile to have the Prometheus dependencies
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency
    swagger:
        default-include-pattern: /api/.*
        title: Smart Learning API
        description: Smart Learning API documentation
        version: 1.0.0
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
