os:
    - linux
services:
    - docker
language: java
node_js:
    - "6.11.0"
jdk:
    - oraclejdk8
sudo: false
cache:
  directories:
    - app/node_modules
    - app/src/main/webapp/bower_components
    - app/gradle-cache
    - app/.gradle
    - app/.yarn-cache
    - $HOME/.gradle
    - $HOME/.yarn-cache
    - $HOME/.m2
    - $HOME/.cache/bower
env:
  global:
    - NODE_VERSION=6.11.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - GRADLE_USER_HOME=gradle-cache
before_install:
    - jdk_switcher use oraclejdk8
    - java -version
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add bower gulp-cli gulp
install:
    - cd app
    - yarn install
script:
    - cd app
    - chmod +x app/gradlew
    - ./gradlew clean test
    - gulp test
    - ./gradlew bootRepackage -x test
    - ./gradlew deployHeroku
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false