os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.11.0"
jdk:
    - oraclejdk8
sudo: false
cache:
  directories:
    - app/node
    - app/node_modules
    - app/gradle-cache
    - $HOME/.gradle
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
    - jdk_switcher use oraclejdk8
    - java -version
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add bower gulp-cli
install:
    - app/yarn install
script:
    - chmod +x app/gradlew
    - app/gradlew clean test
    - app/gulp test
    - app/gradlew bootRepackage -x test
    - app/gradlew deployHeroku
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false