os:
    - linux
services:
    - docker
language: java
node_js:
    - 6.11.0
jdk:
    - oraclejdk8
sudo: false
cache:
    directories:
        - app/node_modules
        - app/gradle-cache
        - app/.gradle
        - app/.yarn-cache
        - "$HOME/.gradle"
        - "$HOME/.yarn-cache"
        - "$HOME/.m2"
env:
    global:
        - NODE_VERSION=6.11.0
        - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
        - GRADLE_USER_HOME=gradle-cache
before_install:
    - jdk_switcher use oraclejdk8
    - java -version
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add bower gulp-cli gulp
install:
    - cd app
    - yarn install
script:
    - pwd
    - chmod +x ./gradlew
    - "./gradlew clean test"
    - gulp test
    - "./gradlew -Pprod clean test"
    - gulp build
    - "./gradlew -Pprod stage -x test"
notifications:
    webhooks:
        on_success: change
        on_failure: always
        on_start: always
