package com.smart.learning.domain.learn;

import com.smart.learning.domain.User;
import com.smart.learning.domain.util.StringBaseDateModel;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * a group of contents customized for a specific student and generated by our algorithms
 */
@Document(collection = "generated_lessons")
public class GeneratedLesson extends StringBaseDateModel {
    private User student;
    //subject that this lessons is linked to
    private Subject subject;
    private List<Content> contents;
    //if null, this is the last term
    private GeneratedLesson next;

    public User getStudent() {
        return student;
    }

    public void setStudent(User student) {
        this.student = student;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public List<Content> getContents() {
        return contents;
    }

    public void setContents(List<Content> contents) {
        this.contents = contents;
    }

    public GeneratedLesson getNext() {
        return next;
    }

    public void setNext(GeneratedLesson next) {
        this.next = next;
    }
}
