version: '2'
services:
    sonar-app:
        image: sonarqube:6.3
        command: /opt/sonarqube/bin/install-plugins.sh
        ports:
            - 9000:9000
            - 9092:9092
        environment:
              - SONARQUBE_JDBC_USERNAME=root
              - SONARQUBE_JDBC_PASSWORD=sonar
              - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
        volumes:
            - ./config/conf:/opt/sonarqube/conf
            - ./config/data:/opt/sonarqube/data
            - ./config/plugins:/opt/sonarqube/extensions/plugins:rw
            - ./config/bash/install-plugins.sh:/opt/sonarqube/bin/install-plugins.sh:ro
            - ./config/bash/wait-for-it.sh:/opt/sonarqube/bin/wait-for-it.sh:ro
        external_links:
            - mysql-db:db

    project-validation:
        extends:
            file: ../app/config/node.yml
            service: base
        volumes:
            - ../../app:/home/docker/project:rw
            - ./config/bash/validate-project.sh:/home/docker/app.sh:ro
            - ./config/bash/wait-for-it.sh:/home/docker/wait-for-it.sh:ro
        external_links:
            - sonar-app:sonar

    mysql-db:
        image: mysql:5.7
        expose:
            - 3306
        ports:
            - 4000:3306
        environment:
            - MYSQL_ROOT_PASSWORD=sonar
            - MYSQL_DATABASE=sonar
            - MYSQL_USER=sonar
            - MYSQL_PASSWORD=sonar