'use strict';

var exports = {
    moduleName: 'gatewayApp',
    app: 'src/main/webapp/',
    dist: 'build/www/',
    swaggerDist: 'build/www/swagger-ui/',
    templates: 'src/main/resources/templates/',
    targetTemplates: 'target/classes/templates/',
    test: 'src/test/javascript/',
    scss: 'src/main/webapp/scss/',
    sassSrc: 'src/main/webapp/scss/**/*.{scss,sass}',
    cssDir: 'src/main/webapp/content/css',
    bower: 'src/main/webapp/bower_components/',
    tmp: 'build/tmp',
    revManifest: 'build/tmp/rev-manifest.json',
    port: 9000,
    apiPort: 8080,
    liveReloadPort: 35729,
    uri: 'http://localhost:',
    languages: [
        'en'
    ],
    constantTemplate: '(function (angular) {\n' +
    '    \'use strict\';\n' +
    '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
    '    angular\n' +
    '        .module(\'<%- moduleName %>\')\n' +
    '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n' +
    '})(angular);\n',
    jsOrder: [
        '**/AppModule.js',
        '**/admin/AdminModule.js',
        '**/admin/AdminRoute.js',
        '**/*Module.js',
        '**/*Constants.js',
        '**/*Provider.js',
        '**/AppConfig.js',
        '**/*Config.js',
        '**/AppRoute.js',
        '**/*Route.js',
        '**/*Service.js',
        '**/*Factory.js',
        '**/*Filter.js',
        '**/*Directive.js',
        '**/*Component.js',
        '**/*Interceptor.js',
        '**/*Handler.js',
        '**/*Controller.js',
        '**/*.js'
    ],
    vendorOrder: [
        '**/jquery.js',
        '**/moment.js',
        '**/angular.js',
        '**/angular-translate.js',
        '**/messageformat.js',
        '**/*angular-translate*.js',
        '**/*angular*.js',
        '**/highcharts.js',
        '**/rangy-core.js',
        '**/*.js'
    ]
};

exports.css = [
    exports.cssDir + '/**/!(error).css'
];

exports.js = [
    exports.app + 'app/AppController.js',
    exports.app + 'app/**/*.js'
];

module.exports = exports;
